webapp/news/models.py
from datetime import datetime
from sqlalchemy.orm import relationship

from webapp.db import db



class News(db.Model):                                       # class News inheritans with .Model (DB SQLite)
    id = db.Column(db.Integer, primary_key=True)            # id news (number)
    title = db.Column(db.String, nullable=False)            # column title
    url = db.Column(db.String, unique=True, nullable=False) # column url
    published = db.Column(db.DateTime, nullable=False)      # column published
    text = db.Column(db.Text, nullable=True)                # text news (nullable=True -> None)

    def comments_count(self):
        return Comment.query.filter(Comment.news_id == self.id).count()

    def __repr__(self):
        return '<News {} {}>'.format(self.title, self.url)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)           # id comment
    text = db.Column(db.Text, nullable=False)               # text comment
    created = db.Column(db.DateTime, nullable=False, default=datetime.now()) # data comment
    
    # create id for news    
    news_id = db.Column(
        db.Integer,                                   # id - integer      
        db.ForeignKey('news.id', ondelete='CASCADE'), # id is ForeignKey, ondelete='CASCADE' - if you del news, to del comments; index=True - index need create  
        index=True
        )
    # create id for user
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
        )
    news = relationship('News', backref='comments')
    user = relationship('User', backref='comments')

    def __repr__(self):
        return '<Comment {}>'.format(self.id)

webapp/news/views.py
from flask import abort, Blueprint, current_app, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required

from webapp.db import db
from webapp.news.forms_commit import CommentForm
from webapp.news.models import Comment, News
from webapp.weather_html import weather_by_city 
from webapp.utils import get_redirect_target


blueprint = Blueprint('news', __name__)


# @app.route('/')                                                 # start flask's object -> app
@blueprint.route('/') 
def index():
    title = current_app.config['PAGE_TITLE']
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])                       # go function weather
    news_list = News.query.filter(News.text.isnot(None)).order_by(News.published.desc()).all()  # go function news
    city_name = current_app.config['WEATHER_DEFAULT_CITY']
    return render_template('news/index.html', page_title=title, weather = weather, city_name = city_name, news_list=news_list) # send to site


# text new's from DB to my site
@blueprint.route('/news/<int:news_id>')
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()

    if not my_news:
        abort(404)
    comment_form = CommentForm(news_id=my_news.id)

    title = current_app.config['PAGE_TITLE']
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    city_name = current_app.config['WEATHER_DEFAULT_CITY']
    # print(comment_form.news_id)
    # return render_template('news/single_news.html', page_title=my_news.title, news=my_news, comment_form=comment_form, weather = weather, city_name = city_name)
    return render_template('news/single_news.html', page_title=title, news_title=my_news.title, news=my_news, comment_form=comment_form, weather = weather, city_name = city_name)


# page for comments
@blueprint.route('/news/comment', methods=['POST'])
@login_required
def add_comment():
    form = CommentForm()
    if form.validate_on_submit():
        # if News.query.filter(News.id == form.news_id.data).first():
        comment = Comment(text=form.comment_text.data, news_id=form.news_id.data, user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash('Comment is added')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('ERROR in field "{}: - {}'.format(
                    getattr(form, field).label.text, 
                    error
                    ))
    return redirect(get_redirect_target())

webapp/templates/news/index.html
{% extends "base.html" %}

{% block content %}
    <div class='row'>
        <div class='col-11'>

            {% include('messages.html') %}
            
            <!-- <h2>_News_</h2> -->
            {%for news in news_list:%}
                <h4><a href="{{ url_for('news.single_news', news_id=news.id) }}">{{news.title}}</a></h4> 
       
                <p>{{ news.published.strftime('%d.%m.%Y') }} | Comments: {{ news.comments_count()}}</p>
                <hr/>
            {%endfor%}
        </div>
        
       <!--  <div class='col-2'>
            <h6>Forecast
                {% if city_name %}
                    {{ city_name }}:
                {% else %}
                    - Service error -
                {% endif %}
            </h6>

            {% if weather %}
                Temperature: {{ weather.temp_C }} (°C)<br>
                Feels Like : {{ weather.FeelsLikeC }} (°C)
            {% else %}
                - Service error -
            {% endif %}            
        </div> -->

        <div class='col-1'>
            {% include('weather.html') %}
        </div>
        
    </div>
{% endblock %}

webapp/templates/news/single_news.html
{% extends "base.html" %}

{% block content %}
    <div class='row'>
        <div class='col-11 news-content'>
            {% include('messages.html') %}
            
            <h3>{{ news_title }}</h3>

            {{ news.text|safe }}

            {% if news.comments %}
                <h3>Comments:</h3>
                {% for comment in news.comments %}
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">{{ comment.text}}</p>
                        <p class="card-text">
                            <small>Published: {{ comment.created.strftime('%d.%m.%Y') }} |</small>
                            <p class="card-text">
                            Autor: {{ comment.user.username }}</small>
                            </p>
                        </p>
                    </div>
                </div>
                {% endfor %}            

            {% endif %}

            {% if current_user.is_authenticated %}

                <form action="{{ url_for('news.add_comment') }}" method="POST">
                    {{ comment_form.hidden_tag() }}
                    <div class="form-group">                    
                        {{ comment_form.comment_text.label }}
                        {{ comment_form.comment_text() }}
                    </div> 
                    {{ comment_form.submit() }}
                </fomr>
           
            {% else %}
                <p>
                    <br>
                    <h4><a href="{{ url_for('user.login', next=request.full_path)}}"><em><strong>Log in</strong></em></a>  <em><strong>to add a comment to the news. </strong></em></h4>
                    <br><br>
                </p>
           {% endif %}
                                     

        </div>
          
        <!-- <div class='col-2'>
            <h5>Other news:</h5>
            
        </div> -->
        <!-- <div class='col-2'>
            <h6>Forecast
                {% if city_name %}
                    {{ city_name }}:
                {% else %}
                    - Service error -
                {% endif %}
            </h6>

            {% if weather %}
                Temperature: {{ weather.temp_C }} (°C)<br>
                Feels Like : {{ weather.FeelsLikeC }} (°C)
            {% else %}
                - Service error -
            {% endif %}            
        </div> -->
        
        <div class='col-1'>
            {% include('weather.html') %}
        </div>

    </div>
{% endblock %}