webapp/admin/views.py
from flask import Blueprint, redirect, flash, render_template
from flask_login import current_user, login_required

from webapp.news.models import News
from webapp.user.decorators import admin_required
from webapp.user.forms import LoginForm
from webapp.user.models import User
from webapp.utils import get_redirect_target



blueprint = Blueprint('admin', __name__, url_prefix='/admin')


# page for admin
# @app.route('/admin')
@blueprint.route('/')
# @login_required
@admin_required
def admin_index():
    if current_user.is_admin:
        flash('Hello admin! (admin/views)')
        title = 'This page is for Administrators only'
        name_user = User.query.filter(User.username.isnot(None)).all() 
        news_count = News.query.filter(News.text.isnot(None)).count()
        
        return render_template('admin/info.html', page_title=title, name_user=name_user, news_count=news_count)
    else:
        flash("You aren't admin.")

webapp/user/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, current_user

from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.utils import get_redirect_target


blueprint = Blueprint('user', __name__, url_prefix='/users')


# user's form
@blueprint.route('/login')
def login():
    if current_user.is_authenticated:                   # if user authenticated
        # return redirect(url_for('news.index'))        # go start page
        return redirect(get_redirect_target())
    title = 'Authorization'
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


# processing login
@blueprint.route('/process-login', methods=['POST'])
# @blueprint.route('/process-login')
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('You are visiting the site!!')
            # return redirect(url_for('news.index'))
            return redirect(get_redirect_target())
        else:
            flash('Name or password not correct.')
            flash('(Caps Lock may be on)')

            return redirect(url_for('user.login'))
    

# user logout
@blueprint.route('/logout')
def logout():
    logout_user()
    flash('You are leaving the site.')
    # return redirect(url_for('news.index'))
    return redirect(get_redirect_target())



# user registration
@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        # return redirect(url_for('news.index'))
        return redirect(get_redirect_target())
    form = RegistrationForm()
    title = 'Registration'
    return render_template('user/registration.html', page_title=title, form=form)


# processing registration
@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('You have registered!')
        return redirect(url_for('user.login'))
        
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('ERROR in field "{}: - {}'.format(
                    getattr(form, field).label.text, 
                    error
                    ))
        return redirect(url_for('user.register'))
    # flash('Please, enter correct data. (user/views.py)')
    # return redirect(url_for('user.register'))

webapp/templates/base.html
<!-- Add news lesson 4_3_5 -->


<!-- Required meta tags -->
<!--  -->
<!-- !doctype html -  for html -->
<!doctype html> 
<!-- html lang="en" - lenduage -->
<html lang="en">
  <head>
    <!-- meta charset="utf-8" - codding site -->
    <meta charset="utf-8">
    <!-- name="viewport" - for view os, android, windows -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--  -->

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">


    <link     href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/monokai-sublime.min.css" rel="stylesheet" >
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>
      <script>hljs.initHighlightingOnLoad();</script>

    <title>{{ page_title }}</title>
    <!-- text_1 -->
  </head>
  
  <body>
    {%  include 'menu.html' %}
    <div class="container">
    <!-- <h5><em><h6> <em>SOME NEWS ABOUT AI.</em></h6>&nbsp;&nbsp;(from <a href="https://www.artificialintelligence-news.com" style="color: black;"> -->
        <!-- <h6><em><h5> <em>SOME NEWS ABOUT AI.</em></h5>&nbsp;&nbsp;(from <a href="https://www.artificialintelligence-news.com" style="color: black;">https://www.artificialintelligence-news.com</a>)</em></h6> <hr/> -->
        <h6 style="display: inline; margin: 0;"><em><h5 style="display: inline; margin: 0;"><em>SOME NEWS ABOUT AI.</em></h5></em></em></h6>&nbsp;&nbsp;<em>(from <a href="https://www.artificialintelligence-news.com" style="color: black;">https://www.artificialintelligence-news.com</a>)</em><hr/>
    <!-- <h5> <em>{{ page_title }}:--_</em> </h5> -->
         {% block content %}{% endblock %}
        
    
    </div>

    <!--  -->
    <!-- Oprional Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>

    <!-- This Javascript  for load better picture from SQl (img data-src)-->
    <script>
    window.addEventListener('DOMContentLoaded', function() {
        var lazyImages = [].slice.call(document.querySelectorAll('img[data-src]'));

        if ('IntersectionObserver' in window) {
            var lazyImageObserver = new IntersectionObserver(function(entries, observer) {
                entries.forEach(function(entry) {
                    if (entry.isIntersecting) {
                        var lazyImage = entry.target;
                        lazyImage.src = lazyImage.dataset.src;
                        lazyImage.removeAttribute('data-src');
                        lazyImageObserver.unobserve(lazyImage);
                    }
                });
            });

            lazyImages.forEach(function(lazyImage) {
                lazyImageObserver.observe(lazyImage);
            });
        } else {
            // Fallback
            lazyImages.forEach(function(lazyImage) {
                lazyImage.src = lazyImage.dataset.src;
                lazyImage.removeAttribute('data-src');
            });
        }
    });
    </script>

  </body>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">

  
  <h6><a class="navbar-brand" href="#"><em>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</em></a></h6>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/"><u>                 </u></a>
        </li>


        <li class="nav-item">
          <h5><a class="nav-link active" aria-current="page" href="/"><u>Start page</u></a></h5>
        </li>


              

      </ul>

      <!-- <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">MySearch</button>
      </form> -->




      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}        
          <li class="nav-item">
            <h5><span class="nav-link">Hello <strong><em>{{ current_user.username }}</em>!</strong></span></h5>
          </li> 

          {% if current_user.is_admin %}
            <li class="nav-item">
              <h5><a class="nav-link" href="{{ url_for('admin.admin_index', next=request.full_path) }}"><u>Administration</u></a></h5>
            </li>
          {% endif %}

          <li class="nav-item">
            <h5><a class="nav-link" href="{{ url_for('user.logout', next=request.full_path) }}"><u>Sign out</u></a></h5>
          </li> 

        {% else %}
          <li class="nav-item">
            <h5><a class="nav-link" href="{{ url_for('user.register') }}"><u>Registration</u></a></h5>
          </li>
          <li class="nav-item">
            <h5><a class="nav-link" href="{{ url_for('user.login', next=request.full_path) }}"><u>Sign in</u></a></h5>
          </li>
        {% endif %}
        
      </ul>

    </div>

  </div>
</nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <p><em>
    <div class='alert alert-warning' role='alert'>
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    </em></p>
    {% endif %}
{% endwith %}

webapp/templates/weather.html
<h5><em>Forecast
    {% if city_name %}
        {{ city_name }}:
    {% else %}
        - Service error -
    {% endif %}
</em></h5>

{% if weather %}

    <!-- <div style="white-space: nowrap;">
    Temperature{{weather.temp_C}}(°C)<br>
    Feels like&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ weather.FeelsLikeC }}(°C)<br>
    Temp max  &nbsp;&nbsp;&nbsp;{{ weather.temp_max }}(°C)<br>
    Temp min  &nbsp;&nbsp;&nbsp;&nbsp;{{ weather.temp_min }}(°C)<br>

    Pressure  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ weather.pressure }}(hPa)<br>
    Humidity  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ weather.humidity }}(%)<br>
    Visibility  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ weather.visibility }}(km)<br>
    Wind speed  {{ weather.wind_speed }}(m/s)<br>
    Direct wind &nbsp;&nbsp;{{ weather.wind_deg }}(&rarr;)<br>
    </div> -->

    <div style="white-space: nowrap;">
    <table>
        <tr>
            <td>Temperature:</td>
            <td>{{ weather.temp_F }}(°F)</td>
            <td>| {{weather.temp_C}}(°C)</td>
        </tr>
        <tr>
            <td>Feels like:</td>
            <td>{{ weather.FeelsLikeF }}(°F)</td>
            <td>| {{ weather.FeelsLikeC }}(°C)</td>
        </tr>
        <tr>
            <td>Temp max:</td>
            <td>{{ weather.temp_maxF }}(°F)</td>
            <td>| {{ weather.temp_max }}(°C)</td>
        </tr>
        <tr>
            <td>Temp min:</td>
            <td>{{ weather.temp_minF }}(°F)</td>
            <td>| {{ weather.temp_min }}(°C)</td>
        </tr>
        <tr>
            <td>Pressure:</td> 
            <td>{{ weather.pressure_inHg }}(in)</td>
            <td>| {{ weather.pressure }}(hPa)</td>
        </tr>        
        <tr>
            <td>Visibility:</td>
            <td>{{ weather.visibility_mi }}(mi)</td>
            <td>| {{ weather.visibility }}(km)</td>
        </tr>
        <tr>
            <td>Wind speed:</td>
            <td>{{ weather.wind_speed_mph }}(mph)</td>
            <td>| {{ weather.wind_speed }}(m/s)</td>
        </tr>
        <tr>
            <td>Humidity:</td>
            <td>{{ weather.humidity }}(%)</td>
        </tr>
        <tr>
            <td>Direction wind:</td>
            <td>{{ weather.wind_deg }}(&rarr;)</td>
        </tr>


    </table>
    </div>
    



     <!-- <p>
    <div style="white-space: nowrap;">
    Temperature:{{weather.temp_C}}(°C)<br>
    Feels like:{{ weather.FeelsLikeC }}(°C)<br>
    Temp max:{{ weather.temp_max }}(°C)<br>

    Temp min:{{ weather.temp_min }}(°C)<br>

    Pressure:{{ weather.pressure }}(hPa)<br>

    Humidity:{{ weather.humidity }}(%)<br>

    Visibility:{{ weather.visibility }}(km)<br>

    Wind speed:{{ weather.wind_speed }}(m/s)<br>
    Direct wind:{{ weather.wind_deg }}(&rarr;)<br>
    </div>
    </p> -->




{% else %}
    - Service error -
{% endif %}    